2013/01/29 22:00:50 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1049] Unknown database 'review_'' in /var/www/review_online/common/lib/yii/db/CDbConnection.php:381
Stack trace:
#0 /var/www/review_online/common/lib/yii/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/review_online/common/lib/yii/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/review_online/common/lib/yii/base/CModule.php(387): CDbConnection->init()
#3 /var/www/review_online/common/lib/yii/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/review_online/common/lib/yii/gii/generators/model/ModelCode.php(57): CModule->__get('db')
#5 /var/www/review_online/common/lib/yii/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/review_online/common/lib/yii/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/review_online/common/lib/yii/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/review_online/common/lib/yii/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/review_online/common/lib/yii/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/review_online/common/lib/yii/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/review_online/common/lib/yii/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/review_online/common/lib/yii/web/CWebApplication.php(282): CController->run('')
#13 /var/www/review_online/common/lib/yii/web/CWebApplication.php(141): CWebApplication->runController('gii/model')
#14 /var/www/review_online/common/lib/yii/base/CApplication.php(169): CWebApplication->processRequest()
#15 /var/www/review_online/font-end/www/index.php(14): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model
HTTP_REFERER=http://www.review.local/index.php?r=gii/default/index
---
